### ISSUE TITLE
Performance with images as reel symbols

### ISSUE THREAD

**Issue by kat0d** [Danziger/slotjs#1]
there is a lags on mobile devices, when you update reel angle with inlined "transform: rotate" style.
It is possible just set spin animation with animation duration ?

**Comment by Danziger** [comment]
Hi @kat0d. This is not nor was intended to be a production-ready project. Actually, it doesn't even use the best technologies for a game (using a canvas would probably be better), it was just something I wanted to try out. If you want to optimize it for some particular reason, feel free to fork the project and read the suggestions I wrote on the README, which _might_ make it perform better.
