### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DweltOfficial** [Danziger/slotjs#29]
Hello, i don't want to bother you or anyone else. 
It's just my first time trying to do this.

Is there some way you can teach us newbies how to completly install this project ?

thank you for answer.

with best regards,

-Dwelt

**Comment by Danziger** [comment]
After cloning the project, just do `npm install` or `yarn install`. Then, `npm start` or `yarn start` to run the project, and you can access it at http://localhost:8080/slotjs/.

**Comment by korzh875** [comment]
@DweltOfficial, Hi

Thanks you for the project


Hot reload is not working(

I change title or text and nothing happens

Whart a problem?

**Comment by korzh875** [comment]
@Danziger , Hi

Thanks you for the project

Hot reload is not working(

I change title or text and nothing happens

Whart a problem?

**Comment by Danziger** [comment]
@korzh875 Hot reloading only works with JS files. CSS / SCSS and HTML / EJS files won't be hot-reloaded.
